rules:
  # 「サーバ」→「サーバー」：語尾の長音符号を統一
  - expected: サーバー
    pattern: /サーバ(?!ー)/
    specs:
      - from: サーバ
        to: サーバー

  # 「アダプタ」→「アダプター」：Astro ドキュメントでは「アダプター」に統一
  - expected: アダプター
    pattern: /(?<!ー)アダプタ(?!ー)/
    specs:
      - from: アダプタ
        to: アダプター

  # 「アキテクチャー」→「アキテクチャ」：長音符号を除いた表記が正規表記
  - expected: アキテクチャ
    pattern: /アキテクチャー/
    specs:
      - from: アキテクチャー
        to: アキテクチャ

  # 「コンテントコレクション」→「コンテンツコレクション」：誤字修正
  - expected: コンテンツコレクション
    patterns:
      - コンテントコレクション

  # 「コントリビュータ」→「コントリビューター」：名詞の表記を統一
  - expected: コントリビューター
    pattern: /(?<!ー)コントリビュータ(?!ー)/
    specs:
      - from: コントリビュータ
        to: コントリビューター

  # 「integration」→「インテグレーション」：Astro の機能名に合わせる
  - expected: インテグレーション
    patterns:
      - integration

  # 「レンダー」→「レンダリング」：動詞としての「render」は「レンダリングする」に統一
  - expected: レンダリング
    pattern: /(?<!ー)レンダー(?!ー)/
    specs:
      - from: レンダー
        to: レンダリング

  # 「イシュー」→「Issue」：GitHub の Issue は英語表記を使用
  - expected: Issue
    pattern: /イシュー(?!ー)/
    specs:
      - from: イシュー
        to: Issue

  # 「プリレンダー／プリレンダリング」→「事前レンダリング」：Astro の用語に統一
  - expected: 事前レンダリング
    patterns:
      - プリレンダー
      - プリレンダリング

  # 「：」→削除：本文中のコロンは不要なので警告を出す
  - expected: ""
    patterns:
      - "："
