# prh.yml - Textlint 用 prh ルール辞書ファイル
# 以下のルールで英語用語を日本語訳に置き換えます

rules:
  - expected: アダプター
    patterns:
      - adapter
      - アダプタ

  - expected: アキテクチャ
    # “architecture” のカタカナ表記では長音符号「ー」を省略します
    patterns:
      - アキテクチャー

  - expected: コンテンツコレクション
    patterns:
      - コンテントコレクション

  - expected: コントリビューター
    # “contributor” は名詞としてのみ訳出します。動詞 “contribute” は「貢献する」など別訳にするため、ここでは対象外です
    patterns:
      - コントリビュータ

  - expected: フロントマター
    # フロントマター概念を指す場合（例: フロントマター セクション）。プロパティ名として使う場合は英字の “frontmatter” のままにします
    patterns:
      - frontmatter

  - expected: インテグレーション
    patterns:
      - integration

  - expected: レンダリング
    # 動詞として使う場合は「レンダリングする」と文章中で書きます
    patterns:
      - レンダー

  - expected: Issue
    patterns:
      - イシュー
    
  - expected: 事前レンダリング
    patterns:
      - プリレンダー
      - プリレンダリング
